name: task_manager
description: A simple task manager app to validate competencies.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.2.1
  fluttertoast: ^8.0.9
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
